### ISSUE TITLE
Load Too Slow and Output Error for Downloading Fonts

### ISSUE THREAD

**Issue by AlexanderInUM** [hku/aigc-webui#1]
I encountered the problem of loading too slow on my PC with GPU 3090 and a RAM of 16GB.
Also it seems that some assets or fonts are failed to be downloaded though I have full internet access.
I could not find where is the asset named "Inter" in the file so I could not download it manually.
The output is shown as below:
```
> aigc-webui@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from D:\Downloaded\AIGCWebUI\.env.local
AbortError: The user aborted a request.
    at abort (D:\Downloaded\AIGCWebUI\node_modules\next\dist\compiled\node-fetch\index.js:1:65190)
    at AbortSignal.abortAndFinalize (D:\Downloaded\AIGCWebUI\node_modules\next\dist\compiled\node-fetch\index.js:1:65410)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:636:26)
    at abortSignal (node:internal/abort_controller:292:10)
    at AbortController.abort (node:internal/abort_controller:323:5)
    at Timeout.<anonymous> (D:\Downloaded\AIGCWebUI\node_modules\next\dist\compiled\@next\font\dist\google\fetch-css-from-google-fonts.js:35:55)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  type: 'aborted'
}
error - Failed to download `Inter` from Google Fonts. Using fallback font instead.
event - compiled client and server successfully in 33.9s (233 modules)
wait  - compiling...
event - compiled successfully in 311 ms (194 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 76.8s (5533 modules)
```

**Comment by hku** [comment]
Have you fixed your problem yet? if the network is ok, there should be no issue like this.
